# College Fit {#slug-two}
Revised for Submission 10.03.2017

#### Keywords

College, Graduation, Fit

## Situtation

According to the National Center for Education Statistics approximately 3.6 mm students will graduate from High School in the 2017-2018 academic year, and traditionally 69% of these will go on to college in the Fall after they graduate. Each year these graduating students who go on to tertiary education are faced with tough choices about which college would be the best fit for them academically, socially, athletically etc.

#### It’s a big problem!

For these 2.5mm students it is reasonable to assume that most of them, at some point, with varying degrees of attention and efficacy, will go through the process of trying to inform their choices about which institution they would like to attend, and deciding on where they would ultimately apply.

Legions of professional advisers – school-based, commercial, and online – have created an industry trying to help applicants find the right fit with colleges – and while the focus of these advisors is also on ‘grooming’ the student for the process – a large part of what they preach and teach is about “fit”.

Students applying to college consistently face a couple of key questions: What is the right school for me?  How likely am I going to be happy there? 

## Problem

For some students, the consideration set of candidate colleges is highly constrained, given financial or geographic limitations, along with whatever academic thresholds need to be met.  For some, the primary question may simply be: Am I able to get in there? or Will I be able to afford this option?  But assuming students have more than one option to choose from, that meet constraints like affordability, location, academic standard etc – they need to evaluate their choices. 

#### This information gathering process is messy and does not work.

For all students in this condition, unless the choice and process of applying was entirely random – they have to consider multiple factors about each institution, deriving information from a variety of sources, including the candidate schools themselves, counsellors, family, friends, web search etc.   Students then have to evaluate what they learn from this information gathering, and weigh it up against some personal criteria they hold that informs the sort of place where they believe or feel they would ‘fit.’   

Substantial data about the level of transfers students make from their original college (~30%), and the growing concerns about the mental health of students, suggest that this process of choosing and matching is far from perfect.  And even if a solution could be found to improve the process on only ‘one-side’ of the equation, i.e. the students process of choice-making – this might have considerable positive outcomes and improve the social good.

#### Little of the information considered is demonstrably linked or correlated with questions of ‘fit’.

Further college is an “experience good” in the sense that potential students have very limited data about what the actual experience of their academic and social life will be before they enter college and "consume" the service -- they can ultimately only “evaluate by purchase”.   This suggests a further need to ‘harden’ the information being used to inform these decisions.

#### Today, there is no reliably ‘algorithmic’ way to support this process. 

The question arises then as to whether there is an algorithmic model capable of leveraging, analyzing and interpreting multiple large sets of data, that could improve this decision-making process and lead to better educational experiences and outcomes for the future generations of students.

## Proposed Solution

In the most simplistic form the service requires two broad sets of data, College-side and Prospective Student-side.  

**COLLEGE SIDE:** The core components of what the college needs to capture and/or track, are: 
> 1. Define various outcomes, or measures of success, and then track these over time for individual students at their schools.  For example, the results of survey questions like "How happy are you at Alpha College", or "How satisfied are you with your choice to attend College U?," or on a scale of 1-5 please rate your experience with" etc.  
> 2. Capture a psycho-social profile of their students as incoming freshman, through a standardized tool like MBTI or DISC. 

These two basic pieces of 'data' are what we need from each participating college.Taken together with other aggregate data about the institution, this information could be used to construct a model that would help predict whether a certain student with a certain profile would be a “good fit” for each of the specific school.  It gives us a model of what 'type' of people have or have not thrived at that institution.

In order to ensure the process appears 'bias-free' i.e., prospective students are confident the data is not being selectively chosen or manipulated, this survey and analysis would be carried out by an independent third party; indeed this third party might be "College Fit" itself - to ensure the maximum ability to generate robust comparable and explicable results.

**PROSPECTIVE STUDENT SIDE**
The key data we are trying to establish from prospective students, are
> 1. Scores from key psychographic tests like MBTI etc, along with responses to some tailored questions about personality, perhaps drawin from the Big 5 Inventory of Personality, and some more descriptive factors about likes and disklikes.
> 2. More 'categorical' data about their up-front or 'going-in' assumptions about areas of definition like "Big" School versus "Small" School," rural versus urban, etc.

### Additional ways to train this model
> The project will attempt to also include in additional available factorS - that purport to evaluate the experience of students. There are a number of more informal websites like Ratemyprofessors.com - which may help with broad categorization of an institution or perhaps an individual academic discipline.  For sites like these, we will need to test several natural language processing alogrithms.  
> Further, we are interested in identifying what data  on individual students already at the prospect college might be gleaned from their Social Media "Graph", and may provide further color on their likes and dislikes at their School, and how that's linked to their 'personality.'
> In addition we would look to explore what synergies might exist with the National Survey of Student Engagement, which measures many factors of student experience including questions like: "If you could start over again, would you go to the same institution you are now attending."  Strong summary metrics like these could be very helpful if they are generally considered reliable and/or an accurate proxy for total experience at at College.

## Product Vision
Students in the process of evaluating and selecting colleges would have a web site, or mobile application, as the interface to "College Fit."  This tool would accomplish three principal tasks.

#### 1. Gather Data 
Enable the student to take a standardized psychometric test like MBTI or DISC, or work through a bank of individual selected psychometric questions.  In additon to fill in some profile questions - demographics, hobbies, interests etc.

#### 2. Apply High Level Filters
Students would be able to make 'category' type selections, e.g., Colleges only in the Northeast, or Colleges over a certain size; although students, at this stage may be encourage to use minimal 'filtering' so that they can let the algorithm do its work.  They may be surprised, for instance, that many students "just like them" thrived at Big Ten Schools, when the prospective student had told him or herself, they had no interest in such institutions.

#### 3. Present Recommendations
Present 5 - 10 recommendations, with some sort of justification or explanation e.g., "We've selected this school for you because people who had a similar strong interest in the outdoors, and considered themselves more extrovert, agreeable, and emotionallly stable.

## Additional Business Opportunities
With the core data collection from current students, evealuating their experience at college etc, much of the insights gleaned could be re-packaged and re-sold back to colleges for other commercial opportunities - for example evaluating what levels of services they need to keep students motivated and engaged; or data that enables colleges to make better choices about applicants etc.
